### ISSUE TITLE
Dates listed in README missing seconds

### ISSUE THREAD

**Issue by vkai** [hoodiehq/hoodie-account-server-api#38]
> "createdAt": "2016-01-01T00:00.000Z"

The ISO formatted dates throughout the `README.md` are improperly formatted, missing the seconds place, i.e. `"2016-01-01T00:00:00.000Z"`. The date returns an `Invalid Date` error when parsed by javascript `Date`.

**Comment by gr2m** [comment]
Good catch @vkai 👍 Do you want to send a pull request for it yourself? Happy to assist if you have any questions

**Comment by vkai** [comment]
Sure I can do it

**Comment by vkai** [comment]
#40

**Comment by gr2m** [comment]
thanks 👍
