### ISSUE TITLE
💯 code coverage

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server-api#46]
The simplest way to increase the code coverage is by generating an HTML-based line coverage report that you can open and browse locally in any browser.

The steps are as follows

1. `npm test`  
    this stores coverage internaly in `.nyc_output`
2. `./node_modules/.bin/nyc report --reporter=lcov`  
    this generates `coverage/lcov-report/`
3. `open coverage/lcov-report/index.html`  
     Open `coverage/lcov-report/index.html` in the browser of your choice

We aim for 100% in all columns: statements, branches, functions and lines. I would suggest you start a pull request as soon as possible and then keep pushing commits that increase the coverage. Please let me know if you have any questions :)

**Comment by gr2m** [comment]
@jeanhl do you still want to work on this?

**Comment by jeanhl** [comment]
Hey Gregor,

Apologies. I just started a new job and won't have the time to properly dedicate to Hoodie anymore. I think it's better if I'm removed from the project for the time being. 

Thank you very much for your guidance, motivation and the wonderful Hoodie community. :)

Thanks again,
Jean

**Comment by gr2m** [comment]
No problem at all, all the best for the new job, and you are welcome back anytime :)

**Comment by capellini** [comment]
@gr2m I can take this, if you'd like.

**Comment by gr2m** [comment]
@capellini thansk Rob, it’s all yours :)
