### ISSUE TITLE
accounts.findAll() throws error if there are accounts

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server-api#56]
Problem is here: https://github.com/hoodiehq/hoodie-account-server-api/blob/2a5785502ffe6301e137dbc66e76757ee8cf8415/lib/accounts/find-all.js#L16

We don’t default `options` to {}

**Comment by mbad0la** [comment]
I'd like to claim this @gr2m 

Can I have a little context about the issue?

**Comment by gr2m** [comment]
@mbad0la all yours :)

What happens in https://github.com/hoodiehq/hoodie-account-server-api/blob/2a5785502ffe6301e137dbc66e76757ee8cf8415/lib/accounts/find-all.js is that it finds all existing accounts in the database. For each account that was found, it returns either only the account properties are includes the `.profile` property, based on if `accounts.findAll({include: 'profile'})` was passed or not. 

Now the problem is that `accounts.findAll()` throws an error that `.include` cannot be accessed because `options` is undefined

What we should do is either to change the check to `options && options.include === 'profile'` or to default `options` to `{}` on the first line if it’s undefined

**Comment by gr2m** [comment]
fixeda via 
https://github.com/hoodiehq/hoodie-account-server-api/issues/57
